title: Annie Hazarika
author:
  name: Annie Hazarika
  email: 'hello.anniehazarika@gmail.com'
metadata:
    description: I'm Annie Hazarika, an illustrator and animator straight outta the mystical land of India.

